### ISSUE TITLE
红外-可见光融合图像观感

### ISSUE THREAD

**Issue by op-dog** [runjia0124/CoCoNet#14]
作者您好，当我在进行红外-可见光图像融合测试时，融合图像的整体锐度比较大，或者说有比较大的噪声（不知道这样理解是否合理），主观观感上有点失真。同时在EN、AG、SF等客观指标结果也比当前一些SOTA方法高出许多，这是否意味着是图像噪声导致了这种结果呢？

**Comment by runjia0124** [comment]
您好，感谢反馈。可能和contrastive finetuning前的阶段有关，也就是backbone还有提升空间，可能会更关注高频部分，事实上我们实验发现contrastive finetuning后这个问题会得到大幅抑制，也进一步证明我们算法的有效性。我们也在积极改善这部分，尤其在低光场景下RGB噪声影响较大的场景。

**Comment by op-dog** [comment]
非常感谢您的回复！

**Comment by op-dog** [comment]
> 较大

非常感谢您的回复！

**Comment by op-dog** [comment]
> 您好，感谢反馈。可能和contrastive finetuning前的阶段有关，也就是backbone还有提升空间，可能会更关注高频部分，事实上我们实验发现contrastive finetuning后这个问题会得到大幅抑制，也进一步证明我们算法的有效性。我们也在积极改善这部分，尤其在低光场景下RGB噪声影响较大的场景。

非常感谢您的回复！
