### ISSUE TITLE
CAM_Module

### ISSUE THREAD

**Issue by GHGluck** [runjia0124/CoCoNet#3]
Hello, can the CAM_Module of the model be made public for testing？ thank you！

**Comment by runjia0124** [comment]
Hi, 
we have added [CAM_Module](https://github.com/runjia0124/CoCoNet/blob/37af75eb90e88ae0b5a957eb3c35b380f2933ea5/attention.py#L54), have fun!

**Comment by GHGluck** [comment]
Thanks for your reply. I still found that the backbone code (self.vgg19 = Vgg19_Unet(vgg19_weights='place_holder') and corresponding pre-training weights are missing during the test. Look forward to your reply. Thank you.

**Comment by runjia0124** [comment]
Sorry for the inconvenience. The code has been updated, please make sure your code is up to date.
