### ISSUE TITLE
Error during testing

### ISSUE THREAD

**Issue by Sharanya0690** [runjia0124/CoCoNet#6]
Hi, I try to run the test code and I am getting this error. I cloned the repository and installed the requirements.txt.

Traceback (most recent call last):
  File "/lustre07/scratch/sharanya/CoCoNet/./main.py", line 3, in <module>
    import cv2
  File "/home/sharanya/.local/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/sharanya/.local/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/imkl/2020.1.217/mkl/lib/intel64/libmkl_intel_lp64.so: undefined symbol: mkl_blas_dsyrk

**Comment by runjia0124** [comment]
> Hi, I try to run the test code and I am getting this error. I cloned the repository and installed the requirements.txt.
> 
> Traceback (most recent call last): File "/lustre07/scratch/sharanya/CoCoNet/./main.py", line 3, in import cv2 File "/home/sharanya/.local/lib/python3.10/site-packages/cv2/**init**.py", line 181, in bootstrap() File "/home/sharanya/.local/lib/python3.10/site-packages/cv2/**init**.py", line 153, in bootstrap native_module = importlib.import_module("cv2") File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/importlib/**init**.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) ImportError: /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/imkl/2020.1.217/mkl/lib/intel64/libmkl_intel_lp64.so: undefined symbol: mkl_blas_dsyrk

Looks like it's a 'cv2' import error, could you first make sure your opencv is well installed and importable? There shouldn't be such error if you have the dependencies configured as in the 'Installation' step.

**Comment by Sharanya0690** [comment]
Hi, thanks!! I found it's due to the version and mismatch between the already installed version. I resolved by changing the version on the requirements.txt file.
