### ISSUE TITLE
关于h5文件

### ISSUE THREAD

**Issue by 19958595306** [runjia0124/CoCoNet#7]
感谢作者的工作，请问训练所用的h5文件要怎么获得呢

**Comment by runjia0124** [comment]
You can crop your own dataset as described in the paper. We use TNO as our training set. I will sort the original data when I get a chance.

**Comment by runjia0124** [comment]
> 感谢作者的工作，请问训练所用的h5文件要怎么获得呢

Hi, please see updates in the Training section.

**Comment by JEDA836** [comment]
> > 感谢作者的工作，请问训练所用的h5文件要怎么获得呢
> 
> Hi, please see updates in the Training section.

你好，具体是在哪啊，怎么通过自己的数据集生成.h5文件
